#!/bin/bash

# FlowKey 多语言功能测试脚本

echo "=== FlowKey 多语言功能测试 ==="
echo "测试时间: $(date)"
echo ""

# 检查应用程序是否运行
if pgrep -f "FlowKey" > /dev/null; then
    echo "✅ FlowKey 应用程序正在运行"
    echo "进程ID: $(pgrep -f FlowKey)"
    echo ""
    echo "🌍 多语言功能测试:"
    echo ""
    echo "支持的语言:"
    echo "1. 🇺🇸 English (默认)"
    echo "2. 🇨🇳 中文"
    echo "3. 🇪🇸 Español"
    echo "4. 🇮🇳 हिन्दी"
    echo "5. 🇸🇦 العربية"
    echo ""
    echo "🧪 测试步骤:"
    echo ""
    echo "1. 打开应用程序窗口"
    echo "   - 检查界面是否以默认语言（英语）显示"
    echo ""
    echo "2. 点击'Open Settings'按钮"
    echo "   - 设置界面应该以当前语言显示"
    echo ""
    echo "3. 在设置中找到'App Language'选项"
    echo "   - 点击下拉菜单选择不同语言"
    echo ""
    echo "4. 测试语言切换:"
    echo "   - 选择 '🇨🇳 中文' → 界面应切换为中文"
    echo "   - 选择 '🇪🇸 Español' → 界面应切换为西班牙语"
    echo "   - 选择 '🇮🇳 हिन्दी' → 界面应切换为印地语"
    echo "   - 选择 '🇸🇦 العربية' → 界面应切换为阿拉伯语"
    echo "   - 选择 '🇺🇸 English' → 界面应切换为英语"
    echo ""
    echo "5. 验证翻译测试功能:"
    echo "   - 点击'Test Translation'按钮"
    echo "   - 弹窗应该以当前语言显示"
    echo "   - 翻译结果应该根据目标语言显示"
    echo ""
    echo "6. 测试按钮功能:"
    echo "   - OK按钮：关闭弹窗并显示通知"
    echo "   - Copy Result按钮：复制翻译结果到剪贴板"
    echo "   - Cancel按钮：关闭弹窗"
    echo ""
    echo "📝 验证命令:"
    echo "测试剪贴板内容:"
    echo "  pbpaste"
    echo ""
    echo "查看应用程序日志:"
    echo "  log show --predicate 'process == \"FlowKey\"' --info --debug --last 5m"
    echo ""
    echo "🔍 多语言实现特性:"
    echo "- 支持5种世界最常用语言"
    echo "- 实时语言切换"
    echo "- 用户设置持久化存储"
    echo "- 完整的UI文本本地化"
    echo "- 系统语言自动检测"
    echo "- 默认语言为英语"
    echo ""
    echo "⚠️  注意事项:"
    echo "- 语言设置会自动保存"
    echo "- 重新启动应用程序会保持上次选择的语言"
    echo "- 部分通知可能仍显示系统语言"
    echo ""
    echo "📊 预期结果:"
    echo "- ✅ 界面文本根据选择的语言实时更新"
    echo "- ✅ 设置界面正确显示语言选项"
    echo "- ✅ 翻译测试弹窗使用当前语言"
    echo "- ✅ 所有按钮响应正常"
    echo "- ✅ 剪贴板功能正常"
    echo ""
else
    echo "❌ FlowKey 应用程序未运行"
    echo "请先启动应用程序:"
    echo "  ./run_app.sh"
    echo "或"
    echo "  ./.build/debug/FlowKey"
    exit 1
fi

echo "=== 测试完成 ==="